import { Applicant } from "./types";

export const applicants: Applicant[] = [
  {
    id: "1",
    name: "Lana Steiner",
    email: "mail@example.com",
    stage: "Applied",
    rating: 3,
    appliedJob: "Sr. Frontend Dev.",
    hasResume: true,
  },
  {
    id: "2",
    name: "Lana Steiner",
    email: "mail@example.com",
    stage: "Interview",
    rating: 4,
    appliedJob: "Software Engineering",
    hasResume: true,
  },
  {
    id: "3",
    name: "Lana Steiner",
    email: "mail@example.com",
    stage: "Evaluation",
    rating: 4,
    appliedJob: "Operations",
    hasResume: true,
  },
  {
    id: "4",
    name: "Lana Steiner",
    email: "mail@example.com",
    stage: "Applied",
    rating: 4,
    appliedJob: "Software Engineering",
    hasResume: true,
  },
  {
    id: "5",
    name: "Lana Steiner",
    email: "mail@example.com",
    stage: "Applied",
    rating: 4,
    appliedJob: "Operations",
    hasResume: true,
  },
  {
    id: "6",
    name: "Lana Steiner",
    email: "mail@example.com",
    stage: "Offer",
    rating: 4,
    appliedJob: "Design",
    hasResume: true,
  },
  {
    id: "7",
    name: "Lana Steiner",
    email: "mail@example.com",
    stage: "Evaluation",
    rating: 3,
    appliedJob: "Finance",
    hasResume: true,
  },
  {
    id: "8",
    name: "Lana Steiner",
    email: "mail@example.com",
    stage: "Contacted",
    rating: 4,
    appliedJob: "Software Engineering",
    hasResume: true,
  },
  {
    id: "9",
    name: "Lana Steiner",
    email: "mail@example.com",
    stage: "Interview",
    rating: 3,
    appliedJob: "Sr. Frontend Dev.",
    hasResume: true,
  },
  {
    id: "10",
    name: "Lana Steiner",
    email: "mail@example.com",
    stage: "Evaluation",
    rating: 4,
    appliedJob: "Software Engineering",
    hasResume: true,
  },
];
