import { Applicant } from "./types";

export const applicants: Applicant[] = [
  {
    id: "1",
    name: "Lana Steiner",
    email: "mail@example.com",
    stage: "Applied",
    rating: 3,
    appliedJob: "Sr. Frontend Dev.",
    hasResume: true,
    aiFitScore: 85,
    source: "LinkedIn",
    dateAdded: "2023-10-15",
  },
  {
    id: "2",
    name: "Lana Steiner",
    email: "mail@example.com",
    stage: "Interview",
    rating: 4,
    appliedJob: "Software Engineering",
    hasResume: true,
    aiFitScore: 92,
    source: "Indeed",
    dateAdded: "2023-10-14",
  },
  {
    id: "3",
    name: "Lana Steiner",
    email: "mail@example.com",
    stage: "Evaluation",
    rating: 4,
    appliedJob: "Operations",
    hasResume: true,
    aiFitScore: 78,
    source: "Referral",
    dateAdded: "2023-10-12",
  },
  {
    id: "4",
    name: "Lana Steiner",
    email: "mail@example.com",
    stage: "Applied",
    rating: 4,
    appliedJob: "Software Engineering",
    hasResume: true,
    aiFitScore: 88,
    source: "LinkedIn",
    dateAdded: "2023-10-10",
  },
  {
    id: "5",
    name: "Lana Steiner",
    email: "mail@example.com",
    stage: "Applied",
    rating: 4,
    appliedJob: "Operations",
    hasResume: true,
    aiFitScore: 75,
    source: "Direct",
    dateAdded: "2023-10-08",
  },
  {
    id: "6",
    name: "Lana Steiner",
    email: "mail@example.com",
    stage: "Offer",
    rating: 4,
    appliedJob: "Design",
    hasResume: true,
    aiFitScore: 90,
    source: "LinkedIn",
    dateAdded: "2023-10-05",
  },
  {
    id: "7",
    name: "Lana Steiner",
    email: "mail@example.com",
    stage: "Evaluation",
    rating: 3,
    appliedJob: "Finance",
    hasResume: true,
    aiFitScore: 82,
    source: "Indeed",
    dateAdded: "2023-10-04",
  },
  {
    id: "8",
    name: "Lana Steiner",
    email: "mail@example.com",
    stage: "Contacted",
    rating: 4,
    appliedJob: "Software Engineering",
    hasResume: true,
    aiFitScore: 95,
    source: "Referral",
    dateAdded: "2023-10-02",
  },
  {
    id: "9",
    name: "Lana Steiner",
    email: "mail@example.com",
    stage: "Interview",
    rating: 3,
    appliedJob: "Sr. Frontend Dev.",
    hasResume: true,
    aiFitScore: 87,
    source: "LinkedIn",
    dateAdded: "2023-09-30",
  },
  {
    id: "10",
    name: "Lana Steiner",
    email: "mail@example.com",
    stage: "Evaluation",
    rating: 4,
    appliedJob: "Software Engineering",
    hasResume: true,
    aiFitScore: 91,
    source: "Direct",
    dateAdded: "2023-09-28",
  },
];
